// modules/registry.js
// ─────────────────────────────────────────────────────────────────────────────
// THE ONLY FILE YOU EDIT when adding a new module.
//
// To add a module:
//   1. Drop its data file into the modules/ folder.
//   2. Add one entry to the correct group below (or create a new group).
//   3. Done — the sidebar and routing update automatically.
//
// Per-group fields:
//   group                  — the group name; self-describing (the technology / layer)
//   icon                   — emoji shown beside the group
//   blurb                  — ONE line: WHERE this group runs (host / VM / container / cluster).
//                            Rendered under the group label so users never have to guess.
//
// Per-module fields:
//   title / subtitle       — shown in the main content header
//   sidebarTitle           — overrides title in the sidebar (optional)
//   sidebarSubtitle        — overrides subtitle in the sidebar (optional)
//   context                — short "where it runs" tag for THIS module (e.g. "host → VM",
//                            "k3s cluster"). Shown as a chip on the card and in the sidebar.
//   Both sidebar fields fall back to title/subtitle when omitted.
// ─────────────────────────────────────────────────────────────────────────────

const MODULE_REGISTRY = [
  {
    group: "Virtual Machines & Provisioning",
    icon: "🛠️",
    blurb: "Build your first DevOps lab on your own laptop: Vagrant + a hypervisor spin up real Linux VMs, then Ansible provisions them — installing packages, deploying apps and managing services over SSH (agentless, nothing left behind on the VMs). The foundation everything later runs on.",
    modules: [
      {
        id: "intro-devops-intro",
        title: "Introduction to DevOps",
        subtitle: "VirtualBox · Vagrant · Manual deploy",
        context: "host → VM",
        script: "modules/intro/devops-intro.js",
        ready: true,
      },
      {
        id: "intro-vagrant-parallels",
        title: "Vagrant + Parallels on M1 Pro",
        subtitle: "Apple Silicon · 32GB RAM · 16 GPU / 10 CPU cores · 1TB SSD · Parallels Desktop Pro",
        sidebarSubtitle: " Two-VM setup on Apple Silicon",
        context: "host → 2 VMs",
        script: "modules/intro/vagrant-parallels.js",
        ready: true,
      },
      {
        id: "intro-vagrant-vmware",
        title: "Vagrant + VMware Fusion on M1 Pro",
        subtitle: "Apple Silicon · 32GB RAM · 16 GPU / 10 CPU cores · 1TB SSD · VMware Fusion",
        sidebarSubtitle: "Two-VM setup on Apple Silicon",
        context: "host → 2 VMs",
        script: "modules/intro/vagrant-vmware.js",
        ready: true,
      },
      {
        id: "intro-practice-vagrant-docker",
        title: "Practice: Provision a Docker VM",
        subtitle: "Hands-on lab · Vagrant + Parallels · ARM64 Ubuntu · install & verify Docker",
        sidebarSubtitle: "Hands-on: a Vagrant Docker host",
        context: "host → VM",
        script: "modules/intro/practice-vagrant-docker.js",
        ready: true,
        practice: true,
      },
      {
        id: "intro-exam",
        title: "Exam: Introduction to DevOps & Vagrant",
        subtitle: "Intro exam · Vagrant + Parallels · author a Vagrantfile · VM lifecycle · provisioning · multi-machine",
        sidebarTitle: "Exam — DevOps & Vagrant",
        sidebarSubtitle: "Intro exam walkthrough",
        context: "host → VM",
        script: "modules/intro/exam-intro.js",
        ready: true,
        practice: true,
      },
      // ── Configuration management with Ansible — still operating on these VMs ──
      {
        id: "ansible-intro",
        title: "Introduction to Ansible",
        subtitle: "Agentless config management · architecture · components · installation",
        sidebarSubtitle: "Agentless config management",
        context: "host (control node)",
        script: "modules/ansible/ansible-intro.js",
        ready: true,
      },
      {
        id: "ansible-inventory-config",
        title: "Inventory & Configuration",
        subtitle: "Inventories · groups · group_vars/host_vars precedence · ansible.cfg",
        sidebarSubtitle: "Inventories, vars & ansible.cfg",
        context: "host (control node)",
        script: "modules/ansible/inventory-config.js",
        ready: true,
      },
      {
        id: "ansible-adhoc-modules",
        title: "Ad-hoc Commands & Modules",
        subtitle: "command vs shell · script module · ansible-doc · package & service modules",
        sidebarSubtitle: "Ad-hoc runs & core modules",
        context: "host → VMs",
        script: "modules/ansible/adhoc-modules.js",
        ready: true,
      },
      {
        id: "ansible-playbooks-dotnet",
        title: "Playbooks — Deploy ASP.NET Core",
        subtitle: ".NET 8 runtime · publish & copy · systemd service · syntax-check · retry files",
        sidebarSubtitle: "Playbooks with a .NET app",
        context: "host → VM (CentOS)",
        script: "modules/ansible/playbooks-dotnet.js",
        ready: true,
      },
      {
        id: "ansible-playbooks-nodejs",
        title: "Playbooks — Deploy Node.js / Express",
        subtitle: "NodeSource · npm ci · systemd service · tags for fast deploys",
        sidebarSubtitle: "Playbooks with a Node.js app",
        context: "host → VM (Ubuntu)",
        script: "modules/ansible/playbooks-nodejs.js",
        ready: true,
      },
      {
        id: "ansible-roles-templates",
        title: "Roles, Templates & Galaxy",
        subtitle: "Role structure · ansible-galaxy · Jinja2 templates · when/facts · register/debug · handlers",
        sidebarSubtitle: "Roles, Jinja2 & advanced techniques",
        context: "host → VMs",
        script: "modules/ansible/roles-templates.js",
        ready: true,
      },
      {
        id: "ansible-practice-lab",
        title: "Practice: Ansible Hands-on Lab",
        subtitle: "Authentic file-for-file lab · Vagrant fleet · ad-hoc → inventory → playbooks → roles · Apache + MariaDB · WinRM finale",
        sidebarTitle: "Practice — Ansible Lab",
        sidebarSubtitle: "Authentic file-for-file lab",
        context: "host → VMs (+ Windows)",
        script: "modules/ansible/practice-ansible-lab.js",
        ready: true,
        practice: true,
      },
      {
        id: "ansible-homework",
        title: "Homework — WEB + DB Stack",
        subtitle: "Two-host heterogeneous deploy · ASP.NET Core / Node.js + PostgreSQL · roles · facts · idempotence",
        sidebarTitle: "Homework — WEB + DB",
        sidebarSubtitle: "Heterogeneous .NET / Node + Postgres",
        context: "host → 2 VMs",
        script: "modules/ansible/homework.js",
        ready: true,
        practice: true,
      },
    ],
  },
  {
    group: "Containers (Docker)",
    icon: "🐳",
    blurb: "Docker Engine on a single host (Raspberry Pi 5, or a VM) — apps packaged as containers.",
    modules: [
      {
        id: "m2-docker-intro",
        title: "Docker on Raspberry Pi 5 (8GB)",
        subtitle: "Raspberry Pi OS installation and configuration",
        context: "Pi 5 host",
        script: "modules/m2/docker-intro.js",
        ready: true,
      },
      {
        id: "m2-advanced-docker",
        title: "Advanced Docker",
        subtitle: "docker-machine · Networking · Volumes · Compose · Swarm (Node.js stack)",
        context: "Docker host",
        script: "modules/m2/advanced-docker.js",
        ready: true,
      },
      {
        id: "m2-docker-compose-dotnet",
        title: ".NET Docker Compose",
        subtitle: ".NET 8 Web API + PostgreSQL multi-container setup",
        sidebarSubtitle: "Compose with a .NET stack",
        context: "Docker host",
        script: "modules/m2/docker-compose-dotnet.js",
        ready: true,
      },
      {
        id: "m2-docker-swarm-dotnet",
        title: ".NET Docker Swarm",
        subtitle: "Deploy .NET services across a 3-node Swarm cluster",
        sidebarSubtitle: "Swarm with a .NET stack",
        context: "Swarm · 3 nodes",
        script: "modules/m2/docker-swarm-dotnet.js",
        ready: true,
      },
      {
        id: "m2-homework",
        title: "Practice: .NET Swarm Deployment",
        subtitle: "Vagrantfile + docker-compose + Swarm cluster exercise",
        sidebarTitle: "Homework — .NET Swarm",
        sidebarSubtitle: "Vagrant + Compose + Swarm",
        context: "host → Swarm VMs",
        script: "modules/m2/homework-m3.js",
        ready: true,
        practice: true,
      },
      {
        id: "m2-nerdctl-intro",
        title: "Nerdctl: Docker-compatible CLI for containerd",
        subtitle: "Installing and using nerdctl on Pi OS",
        context: "Pi 5 host",
        script: "modules/m2/nerdctl-intro.js",
        ready: true,
      },
      {
        id: "m2-practice-docker-images",
        title: "Practice: Build, Run & Optimize Images",
        subtitle: "Hands-on lab · first image · ENTRYPOINT vs CMD · image layers & build cache",
        sidebarSubtitle: "Hands-on: build & optimize images",
        context: "Docker host",
        script: "modules/m2/practice-docker-images.js",
        ready: true,
        practice: true,
      },
      {
        id: "m2-exam",
        title: "Exam: Introduction to Docker",
        subtitle: "M2 exam · install · images & containers · export/import · commit · Dockerfiles · ENTRYPOINT vs CMD · Apache homework",
        sidebarTitle: "Exam — Introduction to Docker",
        sidebarSubtitle: "M2 exam walkthrough",
        context: "Docker host",
        script: "modules/m2/exam-m2.js",
        ready: true,
        practice: true,
      },
    ],
  },
  {
    group: "Orchestration (k3s)",
    icon: "☸️",
    blurb: "A k3s Kubernetes cluster on the Raspberry Pi 5 — containers scheduled across the cluster.",
    modules: [
      {
        id: "k3s-setup",
        title: "Setup Guide for Raspberry Pi 5 (8GB)",
        subtitle: "Running Raspberry Pi OS with k3s and containerized applications",
        context: "Pi 5 cluster",
        script: "modules/k3s-pi5/k3s-pi5.js",
        ready: true,
      },
      {
        id: "k3s-cloudflare-tunnel",
        title: "Cloudflare Tunnel on Pi 5",
        subtitle: "Secure remote access to local services",
        context: "Pi 5 cluster",
        script: "modules/k3s-pi5/cloudflare-tunnel-pi5.js",
        ready: true,
      },
      {
        id: "k3s-dashboard",
        title: "k3s Dashboard",
        subtitle: "Install, create ServiceAccount, generate token, create Ingress, update Cloudflare config",
        context: "k3s cluster",
        script: "modules/k3s-pi5/k3s-dashboard.js",
        ready: true,
      },
      {
        id: "k3s-nginx-ingress",
        title: "Nginx Ingress Controller with Traefik",
        subtitle: "Verify Traefik is running, create Ingress rules, and route traffic to your services",
        context: "k3s cluster",
        script: "modules/k3s-pi5/nginx-ingress.js",
        ready: true,
      },
      {
        id: "k3s-persistent-storage",
        title: "Persistent Storage with k3s",
        subtitle: "Using local-path-provisioner and hostPath for data persistence",
        context: "k3s cluster",
        script: "modules/k3s-pi5/persistent-storage.js",
        ready: true,
      },
      {
        id: "k3s-sample-apps",
        title: "Sample Applications",
        subtitle: "Deploying example workloads to test your k3s cluster",
        context: "k3s cluster",
        script: "modules/k3s-pi5/sample-apps.js",
        ready: true,
      },
      {
        id: "k3s-quick-reference",
        title: "Quick Reference Commands",
        subtitle: "A curated list of essential kubectl commands for managing your k3s cluster",
        context: "k3s cluster",
        script: "modules/k3s-pi5/quick-reference.js",
        ready: true,
      },
      {
        id: "k3s-security",
        title: "Security Notes",
        subtitle: "Best practices for securing your k3s cluster and applications",
        context: "k3s cluster",
        script: "modules/k3s-pi5/security.js",
        ready: true,
      },
      {
        id: "k3s-verification",
        title: "Verification & Testing",
        subtitle: "Commands to verify your cluster and troubleshoot issues",
        context: "k3s cluster",
        script: "modules/k3s-pi5/verification.js",
        ready: true,
      },
      {
        id: "k3s-troubleshooting",
        title: "Troubleshooting",
        subtitle: "Debug common issues with k3s, Traefik, and Cloudflare Tunnel",
        context: "k3s cluster",
        script: "modules/k3s-pi5/troubleshooting.js",
        ready: true,
      }
    ],
  },
  {
    group: "CI/CD",
    icon: "🔄",
    blurb: "Jenkins CI/CD — automated pipelines that build, test, containerise, and deploy .NET and Node.js apps backed by PostgreSQL. Runs on dedicated Vagrant VMs (master + agents).",
    modules: [
      {
        id: "m5-jenkins-intro",
        title: "Introduction to Jenkins",
        subtitle: "CI/CD concepts · architecture · master/agent model · declarative pipelines · Jenkinsfile",
        sidebarSubtitle: "CI/CD concepts & architecture",
        context: "CI server",
        script: "modules/jenkins/jenkins-intro.js",
        ready: true,
      },
      {
        id: "m5-jenkins-setup",
        title: "Jenkins Setup",
        subtitle: "Installation · security · users · plugins · firewall · first-time unlock",
        sidebarSubtitle: "Install, secure & configure",
        context: "CI server",
        script: "modules/jenkins/jenkins-setup.js",
        ready: true,
      },
      {
        id: "m5-jenkins-jobs",
        title: "Jenkins Jobs",
        subtitle: "Freestyle projects · local/remote builds · schedules · GitHub · parameters · PostgreSQL health checks",
        sidebarSubtitle: "Build jobs & triggers",
        context: "CI server",
        script: "modules/jenkins/jenkins-jobs.js",
        ready: true,
      },
      {
        id: "m5-jenkins-slaves",
        title: "Jenkins Slave Nodes",
        subtitle: "Agent topology · SSH launch method · labels · .NET / Node.js builds on dedicated agents",
        sidebarSubtitle: "Distributed build agents",
        context: "CI server → agents",
        script: "modules/jenkins/jenkins-slaves.js",
        ready: true,
      },
      {
        id: "m5-jenkins-docker",
        title: "Jenkins + Docker",
        subtitle: "Docker on agents · image builds · container smoke tests · GitHub → Docker pipeline · cleanup",
        sidebarSubtitle: "Containerised CI/CD",
        context: "CI server → Docker",
        script: "modules/jenkins/jenkins-docker.js",
        ready: true,
      },
      {
        id: "m5-jenkins-pipelines",
        title: "Jenkins Pipelines",
        subtitle: "Declarative Jenkinsfile · .NET & Node.js examples · PostgreSQL integration tests · master/slave orchestration",
        sidebarSubtitle: "Pipeline as Code",
        context: "CI server (Jenkinsfile)",
        script: "modules/jenkins/jenkins-pipelines.js",
        ready: true,
      },
      {
        id: "m5-homework",
        title: "Homework M5 — CI/CD Pipeline",
        subtitle: "Master + slave · Docker · .NET or Node.js · PostgreSQL · full pipeline: checkout → build → test → containerise → deploy",
        sidebarTitle: "Homework — CI/CD",
        sidebarSubtitle: "End-to-end pipeline",
        context: "CI server → 2 VMs",
        script: "modules/jenkins/homework.js",
        ready: true,
        practice: true,
      },
    ],
  },
  {
    group: "Monitoring",
    icon: "📡",
    blurb: "Nagios Core — infrastructure and application monitoring. Watches your .NET / Node.js APIs, PostgreSQL databases, and Docker containers. Alerts you before your users notice.",
    modules: [
      {
        id: "monitoring-nagios-intro",
        title: "Introduction to Nagios",
        subtitle: "Monitoring concepts · Nagios architecture · state model · the monitoring landscape · agents vs agentless",
        sidebarSubtitle: "Monitoring concepts & architecture",
        context: "monitoring host",
        script: "modules/monitoring/nagios-intro.js",
        ready: true,
      },
      {
        id: "monitoring-nagios-setup",
        title: "Nagios Setup",
        subtitle: "Installation · Vagrant environment · plugins · web UI · admin user · HTTP health checks (.NET & Node.js)",
        sidebarSubtitle: "Install, configure & first checks",
        context: "monitoring host",
        script: "modules/monitoring/nagios-setup.js",
        ready: true,
      },
      {
        id: "monitoring-nagios-config",
        title: "Nagios Configuration",
        subtitle: "Hosts · services · host groups · service groups · commands · macros · templates · PostgreSQL monitoring",
        sidebarSubtitle: "Hosts, services & groups",
        context: "monitoring host",
        script: "modules/monitoring/nagios-config.js",
        ready: true,
      },
      {
        id: "monitoring-nagios-remote",
        title: "Remote Monitoring (NRPE)",
        subtitle: "NRPE agent installation · allowed_hosts · remote CPU/disk checks · Nagios → NRPE communication",
        sidebarSubtitle: "Agent-based remote checks",
        context: "monitoring host → agents",
        script: "modules/monitoring/nagios-remote.js",
        ready: true,
      },
      {
        id: "monitoring-nagios-advanced",
        title: "Advanced Nagios",
        subtitle: "PostgreSQL monitoring · Docker container checks · custom plugins · NRPE sudo & docker group",
        sidebarSubtitle: "DB & container monitoring",
        context: "monitoring host → agents",
        script: "modules/monitoring/nagios-advanced.js",
        ready: true,
      },
      {
        id: "monitoring-homework",
        title: "Homework — Automated Nagios Environment",
        subtitle: "3-node Vagrant · shell provisioners · Nagios + Icinga · PostgreSQL · Docker · NRPE · zero manual steps",
        sidebarTitle: "Homework — Monitoring",
        sidebarSubtitle: "Fully automated monitoring",
        context: "monitoring host → 2 VMs",
        script: "modules/monitoring/homework.js",
        ready: true,
        practice: true,
      },
    ],
  },
  {
    group: "Cloud (AWS)",
    icon: "☁️",
    blurb: "AWS — EC2 virtual machines, IAM identity, CLI automation, Vagrant cloud provisioning, and ECS Docker containers. Runs in the cloud (not locally); free-tier compatible with cost warnings throughout. Azure and GCP providers can be added later.",
    modules: [
      {
        id: "aws-intro",
        title: "Introduction to AWS",
        subtitle: "Cloud concepts · SaaS/PaaS/IaaS · the big three · regions & AZs · core services · free tier",
        sidebarSubtitle: "Cloud & AWS fundamentals",
        context: "AWS account",
        script: "modules/cloud/aws-intro.js",
        ready: true,
      },
      {
        id: "aws-ec2",
        title: "AWS EC2",
        subtitle: "Launch instances · security groups · key pairs · user data bootstrap · .NET & Node.js on EC2",
        sidebarSubtitle: "Virtual machines in the cloud",
        context: "AWS EC2",
        script: "modules/cloud/aws-ec2.js",
        ready: true,
      },
      {
        id: "aws-iam-cli",
        title: "AWS IAM & CLI",
        subtitle: "IAM users/groups/policies · AWS CLI setup · describe-images · run-instances · query with JMESPath",
        sidebarSubtitle: "Identity & command-line",
        context: "AWS CLI",
        script: "modules/cloud/aws-iam-cli.js",
        ready: true,
      },
      {
        id: "aws-vagrant",
        title: "Vagrant + AWS",
        subtitle: "Vagrant AWS plugin · dummy box · Vagrantfile for EC2 · bootstrap scripts · vagrant up/destroy on EC2",
        sidebarSubtitle: "Infrastructure as code (cloud)",
        context: "AWS via Vagrant",
        script: "modules/cloud/aws-vagrant.js",
        ready: true,
      },
      {
        id: "aws-ecs",
        title: "AWS ECS (Docker)",
        subtitle: "ECS concepts · task definitions · .NET & Node.js containers · services vs run-task · Fargate vs EC2",
        sidebarSubtitle: "Managed Docker on AWS",
        context: "AWS ECS",
        script: "modules/cloud/aws-ecs.js",
        ready: true,
      },
      {
        id: "aws-homework",
        title: "Homework — Multi-Tier on AWS",
        subtitle: "Replicate a WEB+DB stack on EC2 · .NET or Node.js · PostgreSQL · security groups · free tier · cost-aware cleanup",
        sidebarTitle: "Homework — AWS",
        sidebarSubtitle: "Cloud deployment capstone",
        context: "AWS EC2 → 2 instances",
        script: "modules/cloud/aws-homework.js",
        ready: true,
        practice: true,
      },
    ],
  },
  // ── Add more groups / modules here as you convert the MD files ────────────
];
