name: Validate Labs

on:
  push:
    branches: [main]
    paths:
      - 'labs/**'
  pull_request:
    branches: [main]
    paths:
      - 'labs/**'
  workflow_dispatch:

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3
        with:
          dockerfile: |
            labs/docker/1-hello-world/Dockerfile
            labs/docker/2-nginx-layers/nginx-1/Dockerfile
            labs/docker/2-nginx-layers/nginx-2/Dockerfile
            labs/docker/3-entrypoint-cmd/Dockerfile

  vagrant-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-vagrant@v3
      - run: vagrant validate labs/vms/1-vagrant-docker/Vagrantfile

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: './labs'
